### PR TITLE
add an ability to specify extra topic

### PR DESCRIPTION
**Pull request by ssbb**
Related to #43 

Please let me know what you think about this approach.

### CODE REVIEW

**Comment by ssbb** [comment]
@saschatimme  API here will be like 

```
|> Channel.withExtraTopic "__absinthe__:doc:62645988"
```
without specific message. My example usage looks like this:

```
channels : Maybe String -> List (Channel.Channel Msg)
channels subscriptionId =
    [ Channel.init "__absinthe__:control"
        |> Channel.on "subscription:data" SubscriptionData
        |> (Maybe.map Channel.withExtraTopic subscriptionId
                |> Maybe.withDefault identity
           )
    ]
```

So I will get `SubscriptionData` message if it will appears with both `__absinthe__:control` and my subscription topic.

I am not sure if it's a correct solution. In this approach we just adding "aliases" to topic. As you can see in issue #43 screenshot when `subscription:data` appears it contains `subscriptionId`. Each subscription have it's own id. So we can map it do something like you proposed in original issue:

```
|> Channel.onAbsintheSubscription subscriptionId MessageReceived
```

But I have no idea if you want to include Absinthe-related functionality here (we will need to handle messages like `subscription:data`) or keep it just for Phoenix.

**Comment by ssbb** [comment]
At same time with aliases approach it still possible to handle per-subscription messages, just not in this lib. So I can maintain some dict like `Dict Msg` with keys as subscription id and forward messages. Or even dict with decoders.

**Comment by saschatimme** [comment]
This looks good in principle, but I think you should provide not only a topic but also a `Msg`. What happens if you have joined multiple channels and one extra tropic? In your current implementation you just take the callback for the first channel and dispatch the content on this channel. I see that this works in your situation but in general I think it would be better to make this explicit and to pass a dedicated callback.
In the end the only difference to the `on` case is that there is no joining / leaving, isn't it?
I think just switch your `Set` to a `Dict` and we're a good here :)

Now to the bikeshedding part: I am fine with a generic name, which should probably start with `on...` to be coherent with the rest of the API. But I currently cannot come up with a good name.

**Comment by ssbb** [comment]
@saschatimme good point. How do you think it should be combined with `event`? So for example we joined `__absinthe__:control` channel. And `subscription:data` event will appear under different topic. Should we have another `on` then? Like:

```
|> onWithOtherTopic "__absinthe__:doc:62645988" "subscription:data" MessageReceived
```

What you think about this?

**Comment by ssbb** [comment]
I just can't get an idea of using this (offered by you in #43 issue)

```
|> Channel.onAbsintheSubscription subscriptionId MessageReceived
```

What I will get in `MessageReceived` then? How I can associate it with event?

**Comment by saschatimme** [comment]
Maybe something like `Phoenix.Topic` type?
Then you could do
```elm
topic =
    Topic "__absinthe__:doc:62645988"
    |> Topic.on "subscription:data" MessageReceived

...
|> Channel.additionalTopic topic
```

**Comment by ssbb** [comment]
Thank you! Will try to implement something like this.

**Comment by ssbb** [comment]
Hi! Sorry, did not work on this for a long time since we are using local fork (what first PR looks like) and it solves problems we had. And not sure if it makes sense to work on this PR because of coming 0.19 -Native or Effect managers is not allowed so it will be complete re-write of this library.

**Pull request closed without merging**
